version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL=${OPENAI_MODEL:-gpt-4o-mini}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.2}
    ports:
      - "8000:8000"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_BASE_URL=http://api:8000
    ports:
      - "${WEB_PORT:-3000}:3000"
    depends_on:
      - api
    restart: unless-stopped
